repositories:
    - name: bitnami
      url: https://charts.bitnami.com/bitnami

environments:
  default:

releases:
  - name: database
    namespace: workshop
    chart: bitnami/mysql
    createNamespace: true
    values:
      # use helm secrets plugin for non-workshop use cases
      # https://github.com/zendesk/helm-secrets
      - auth:
          database: wordpress
          username: "wordpress"
          password: "secret"

  - name: wordpress
    namespace: workshop
    chart: bitnami/wordpress
    values:
      - "environments/{{ .Environment.Name }}/values.yaml"
